theme: jekyll-theme-midnight
repository: SWG-Source/SWG-Source.github.io
title: SWG Source
description: Run your own private SWG Server (and help us develop it!)
collections:
  docs:
    output: true
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
    values:
      layout: "default"
